const tstRoster = [
    {
      "position_txt": "1B",
      "weight": "245",
      "name_display_first_last": "Pete Alonso",
      "college": "Florida",
      "height_inches": "3",
      "starter_sw": "N",
      "jersey_number": "20",
      "end_date": "",
      "name_first": "Peter",
      "bats": "R",
      "team_code": "nyn",
      "height_feet": "6",
      "pro_debut_date": "2019-03-28T00:00:00",
      "status_code": "A",
      "primary_position": "3",
      "birth_date": "1994-12-07T00:00:00",
      "team_abbrev": "NYM",
      "throws": "R",
      "team_name": "New York Mets",
      "name_display_last_first": "Alonso, Pete",
      "name_use": "Pete",
      "player_id": "624413",
      "name_last": "Alonso",
      "team_id": "121",
      "start_date": "2019-03-28T00:00:00",
      "name_full": "Alonso, Pete"
    },
    {
      "position_txt": "P",
      "weight": "265",
      "name_display_first_last": "Dellin Betances",
      "college": "",
      "height_inches": "8",
      "starter_sw": "N",
      "jersey_number": "68",
      "end_date": "",
      "name_first": "Dellin",
      "bats": "R",
      "team_code": "nyn",
      "height_feet": "6",
      "pro_debut_date": "2011-09-22T00:00:00",
      "status_code": "A",
      "primary_position": "1",
      "birth_date": "1988-03-23T00:00:00",
      "team_abbrev": "NYM",
      "throws": "R",
      "team_name": "New York Mets",
      "name_display_last_first": "Betances, Dellin",
      "name_use": "Dellin",
      "player_id": "476454",
      "name_last": "Betances",
      "team_id": "121",
      "start_date": "2019-12-24T00:00:00",
      "name_full": "Betances, Dellin"
    }
]

export default tstRoster